/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import javax.swing.text.PlainDocument;
import napakalaki_java.*;

/**
 *
 * @author alvaro89
 */
public class NapakalakiView extends javax.swing.JFrame {

    private Napakalaki napakalakiModel;
    
    /**
     * Creates new form NapakalakiView
     */
    
    public void setNapakalaki(Napakalaki np){
        napakalakiModel = np;
        playerView1.setNapakalaki(np);
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        combat.setEnabled(false);
        nextTurn.setEnabled(false);
        playerView1.Robar.setEnabled(false);
        playerView1.discardAlltreasures.setEnabled(false);
        playerView1.discardTreasures.setEnabled(false);
        monsterView1.setVisible(false);
    }
    
    public NapakalakiView() {
        initComponents();
        setLocationRelativeTo(null);
        this.setTitle("NapakalakiGame");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerView1 = new GUI.PlayerView();
        monsterView1 = new GUI.MonsterView();
        meetMonster = new javax.swing.JButton();
        nextTurn = new javax.swing.JButton();
        combat = new javax.swing.JButton();
        narrador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        meetMonster.setText("Mostrar al monstruo");
        meetMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meetMonsterActionPerformed(evt);
            }
        });

        nextTurn.setText("Pasar Turno");
        nextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnActionPerformed(evt);
            }
        });

        combat.setText("¡ Combatir!");
        combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatActionPerformed(evt);
            }
        });

        narrador.setEditable(false);
        narrador.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        narrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narradorActionPerformed(evt);
            }
        });

        jLabel2.setText("Narrador:");

        jLabel1.setText("Monstruo Actual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(46, 46, 46)
                .addComponent(narrador, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(meetMonster, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combat, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nextTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(narrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerView1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(nextTurn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meetMonster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combat)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnActionPerformed
        if(!napakalakiModel.nextTurn())
            narrador.setText("No cumples los requisitos para pasar turno.");
        else{
            playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
            combat.setEnabled(false);
            nextTurn.setEnabled(false);
            playerView1.Robar.setEnabled(false);
            playerView1.discardAlltreasures.setEnabled(false);
            playerView1.discardTreasures.setEnabled(false);
            monsterView1.setVisible(false);
            narrador.setText("");
            meetMonster.setEnabled(true);
            playerView1.pendingBadConsequenceView1.texto.setText("");
        }
    }//GEN-LAST:event_nextTurnActionPerformed

    private void meetMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meetMonsterActionPerformed
        monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        combat.setEnabled(true);
        monsterView1.setVisible(true);
        meetMonster.setEnabled(false);
        playerView1.makeVisible.setEnabled(false);
    }//GEN-LAST:event_meetMonsterActionPerformed

    private void combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatActionPerformed
        CombatResult resultado = napakalakiModel.developCombat();
        if(resultado == CombatResult.LOSE)
            narrador.setText("Has perdido...");
        else if(resultado == CombatResult.LOSEANDCONVERT)
            narrador.setText("Has perdido y te has convertido en un sectario");
        else if(napakalakiModel.endOfGame(resultado)){
            narrador.setText("¡¡Has ganado el juego!!");
            combat.setEnabled(false);
            nextTurn.setEnabled(false);
            meetMonster.setEnabled(false);
            playerView1.Robar.setEnabled(false);
            playerView1.discardAlltreasures.setEnabled(false);
            playerView1.discardTreasures.setEnabled(false);
            playerView1.makeVisible.setEnabled(false);
        }    
        else if(resultado == CombatResult.WIN)
            narrador.setText("Has ganado.");
           
        playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        combat.setEnabled(false);
        nextTurn.setEnabled(true);
        playerView1.Robar.setEnabled(true);
        playerView1.discardAlltreasures.setEnabled(true);
        playerView1.discardTreasures.setEnabled(true);
        playerView1.makeVisible.setEnabled(true);

    }//GEN-LAST:event_combatActionPerformed

    private void narradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_narradorActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showView() {
        this.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton meetMonster;
    private GUI.MonsterView monsterView1;
    public javax.swing.JTextField narrador;
    private javax.swing.JButton nextTurn;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
